name: Deploy CDK

# Prevent overlapping deploys
concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: false

on:
  workflow_run:
    workflows: ['Build']
    types: [completed]
jobs:
  deploy:
    timeout-minutes: 10
    env:
      AWS_REGION: us-east-1
      MOMENTS_APP_STACK_NAME: MomentsAppStack
      POETRY_VERSION: 2.1.4
      PYTHON_VERSION: 3.12.3
    environment: dev
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:

      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@00943011d9042930efac3dcd3a170e4273319bc8 # v5.1.0
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Read versions
        run: |
          echo "PYTHON_VERSION=$(awk '/^python /{print $2}' .tool-versions)" >> $GITHUB_ENV
          echo "POETRY_VERSION=$(awk '/^poetry /{print $2}' .tool-versions)" >> $GITHUB_ENV

      - name: Setup Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: poetry
          cache-dependency-path: poetry.lock
      - name: Install Poetry
        uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a # v1.4.1
        with:
          version: ${{env.POETRY_VERSION}}
      - name: Install Python deps (includes aws-cdk-aws-lambda-python-alpha)
        run: poetry install --no-interaction --no-root

      - name: CDK Synth
        uses: scottbrenner/aws-cdk-action@23d726e4c8daaf8c47aac36b6f9d75b661b62bac # v1.6.8
        with:
          args: synth

      - name: CDK Deploy Stack
        uses: scottbrenner/aws-cdk-action@23d726e4c8daaf8c47aac36b6f9d75b661b62bac # v1.6.8
        with:
          args: deploy ${{ env.MOMENTS_APP_STACK_NAME }} --require-approval never
